export const COMPETITIONS = [
  { cat: "🌍 Mondial & Nations", items: [
    { id: 1,   name: "Coupe du Monde FIFA",    flag: "🌍", type: "cup",      nat: true },
    { id: 4,   name: "Euro UEFA",              flag: "🇪🇺", type: "cup",      nat: true },
    { id: 6,   name: "Copa América",           flag: "🌎", type: "cup",      nat: true },
    { id: 29,  name: "CAN (Africa Cup)",       flag: "🌍", type: "cup",      nat: true },
    { id: 10,  name: "Ligue des Nations UEFA", flag: "🇪🇺", type: "friendly", nat: true },
    { id: 25,  name: "Amicaux Internationaux", flag: "🤝", type: "friendly", nat: true },
    { id: 32,  name: "Jeux Olympiques",        flag: "🏅", type: "cup",      nat: true },
  ]},
  { cat: "⭐ Coupes d'Europe", items: [
    { id: 2,   name: "Champions League",       flag: "⭐", type: "cup" },
    { id: 3,   name: "Europa League",          flag: "🟠", type: "cup" },
    { id: 848, name: "Conference League",      flag: "🟣", type: "cup" },
    { id: 531, name: "Super Coupe UEFA",       flag: "🏆", type: "cup" },
  ]},
  { cat: "🇫🇷 France", items: [
    { id: 61,  name: "Ligue 1",                flag: "🇫🇷", type: "league" },
    { id: 62,  name: "Ligue 2",                flag: "🇫🇷", type: "league" },
    { id: 63,  name: "National (D3)",          flag: "🇫🇷", type: "league" },
    { id: 65,  name: "Coupe de France",        flag: "🇫🇷", type: "cup"    },
    { id: 66,  name: "Coupe de la Ligue",      flag: "🇫🇷", type: "cup"    },
  ]},
  { cat: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Angleterre", items: [
    { id: 39,  name: "Premier League",         flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", type: "league" },
    { id: 40,  name: "Championship (D2)",      flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", type: "league" },
    { id: 41,  name: "League One (D3)",        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", type: "league" },
    { id: 42,  name: "League Two (D4)",        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", type: "league" },
    { id: 45,  name: "FA Cup",                 flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", type: "cup"    },
    { id: 48,  name: "League Cup (Carabao)",   flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", type: "cup"    },
  ]},
  { cat: "🇪🇸 Espagne", items: [
    { id: 140, name: "La Liga",                flag: "🇪🇸", type: "league" },
    { id: 141, name: "Segunda División (D2)",  flag: "🇪🇸", type: "league" },
    { id: 142, name: "Primera RFEF (D3)",      flag: "🇪🇸", type: "league" },
    { id: 143, name: "Copa del Rey",           flag: "🇪🇸", type: "cup"    },
    { id: 556, name: "Super Coupe Espagne",    flag: "🇪🇸", type: "cup"    },
  ]},
  { cat: "🇩🇪 Allemagne", items: [
    { id: 78,  name: "Bundesliga",             flag: "🇩🇪", type: "league" },
    { id: 79,  name: "2. Bundesliga (D2)",     flag: "🇩🇪", type: "league" },
    { id: 80,  name: "3. Liga (D3)",           flag: "🇩🇪", type: "league" },
    { id: 81,  name: "DFB Pokal",             flag: "🇩🇪", type: "cup"    },
  ]},
  { cat: "🇮🇹 Italie", items: [
    { id: 135, name: "Serie A",                flag: "🇮🇹", type: "league" },
    { id: 136, name: "Serie B (D2)",           flag: "🇮🇹", type: "league" },
    { id: 137, name: "Serie C (D3)",           flag: "🇮🇹", type: "league" },
    { id: 139, name: "Coppa Italia",           flag: "🇮🇹", type: "cup"    },
  ]},
  { cat: "🇵🇹 Portugal", items: [
    { id: 94,  name: "Primeira Liga",          flag: "🇵🇹", type: "league" },
    { id: 95,  name: "Segunda Liga (D2)",      flag: "🇵🇹", type: "league" },
    { id: 96,  name: "Taça de Portugal",       flag: "🇵🇹", type: "cup"    },
  ]},
  { cat: "🇳🇱 Pays-Bas", items: [
    { id: 88,  name: "Eredivisie",             flag: "🇳🇱", type: "league" },
    { id: 89,  name: "Eerste Divisie (D2)",    flag: "🇳🇱", type: "league" },
    { id: 90,  name: "KNVB Beker",             flag: "🇳🇱", type: "cup"    },
  ]},
  { cat: "🇧🇪 Belgique", items: [
    { id: 144, name: "Pro League",             flag: "🇧🇪", type: "league" },
    { id: 145, name: "Division 1B (D2)",       flag: "🇧🇪", type: "league" },
    { id: 146, name: "Coupe de Belgique",      flag: "🇧🇪", type: "cup"    },
  ]},
  { cat: "🇹🇷 Turquie / 🇷🇺 Russie / 🇬🇷 Grèce", items: [
    { id: 203, name: "Süper Lig (Turquie)",    flag: "🇹🇷", type: "league" },
    { id: 235, name: "Premier League Russie",  flag: "🇷🇺", type: "league" },
    { id: 197, name: "Super League Grèce",     flag: "🇬🇷", type: "league" },
    { id: 179, name: "Premiership (Écosse)",   flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", type: "league" },
  ]},
  { cat: "🌎 Amériques", items: [
    { id: 71,  name: "Série A (Brésil)",       flag: "🇧🇷", type: "league" },
    { id: 72,  name: "Série B (Brésil D2)",    flag: "🇧🇷", type: "league" },
    { id: 11,  name: "Copa Libertadores",      flag: "🌎", type: "cup"    },
    { id: 13,  name: "Copa Sudamericana",      flag: "🌎", type: "cup"    },
    { id: 253, name: "MLS (USA)",              flag: "🇺🇸", type: "league" },
    { id: 262, name: "Liga MX (Mexique)",      flag: "🇲🇽", type: "league" },
    { id: 128, name: "Liga Prof. Argentine",   flag: "🇦🇷", type: "league" },
    { id: 239, name: "Primera División Uruguay",flag: "🇺🇾", type: "league" },
    { id: 265, name: "Primera División Chili", flag: "🇨🇱", type: "league" },
    { id: 242, name: "Primera A Colombie",     flag: "🇨🇴", type: "league" },
  ]},
  { cat: "🌍 Afrique", items: [
    { id: 12,  name: "CAF Champions League",   flag: "🌍", type: "cup"    },
    { id: 20,  name: "CAF Confed. Cup",        flag: "🌍", type: "cup"    },
    { id: 233, name: "Botola Pro (Maroc)",      flag: "🇲🇦", type: "league" },
    { id: 200, name: "Egyptian Premier League",flag: "🇪🇬", type: "league" },
    { id: 264, name: "Ligue Pro (Algérie)",    flag: "🇩🇿", type: "league" },
    { id: 263, name: "Ligue 1 (Tunisie)",      flag: "🇹🇳", type: "league" },
    { id: 292, name: "NPFL (Nigeria)",         flag: "🇳🇬", type: "league" },
  ]},
  { cat: "🌏 Asie / Moyen-Orient", items: [
    { id: 36,  name: "AFC Champions League",   flag: "🌏", type: "cup"    },
    { id: 307, name: "Saudi Pro League",       flag: "🇸🇦", type: "league" },
    { id: 98,  name: "J1 League (Japon)",      flag: "🇯🇵", type: "league" },
    { id: 169, name: "K League 1 (Corée)",     flag: "🇰🇷", type: "league" },
    { id: 480, name: "Chinese Super League",   flag: "🇨🇳", type: "league" },
    { id: 323, name: "Persian Gulf Pro (Iran)",flag: "🇮🇷", type: "league" },
  ]},
]

export const ALL_COMPS = COMPETITIONS.flatMap(c => c.items)
